author/models.py
from application import db


class Author(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(80))
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(128))

    def __init__(self, full_name, email, password):
        self.full_name = full_name
        self.email = email
        self.password = password

    def __repr__(self):
        return f"<Author {self.full_name}>"

author/forms.py
from flask_wtf import FlaskForm

from wtforms import validators
from wtforms import StringField
from wtforms import PasswordField
from wtforms import ValidationError
from wtforms.fields import EmailField

from werkzeug.security import check_password_hash

from author.models import Author


class RegisterForm(FlaskForm):
    full_name = StringField("Full Name", [validators.InputRequired()])
    email = EmailField("Email address", [
                       validators.InputRequired(), validators.Email()])
    password = PasswordField(
        "New Password", [validators.InputRequired(), validators.Length(min=4, max=80)])
    confirm = PasswordField("Repeat Password", [validators.EqualTo(
        fieldname='password', message="Passwords must match")])

    def validate_email(self, email):
        author = Author.query.filter_by(email=email.data).first()
        if author is not None:
            raise ValidationError(
                message="Email already in use, please use a different one.")


class LoginForm(FlaskForm):
    email = EmailField("Email address", [
                       validators.InputRequired(), validators.Email()])
    password = PasswordField(
        "New Password", [validators.InputRequired(), validators.Length(min=4, max=80)])

    def validate(self):
        is_valid = FlaskForm.validate(self)
        if not is_valid:
            return False

        author = Author.query.filter_by(email=self.email.data).first()

        if author:
            if not check_password_hash(author.password, self.password.data):
                self.password.errors.append("Incorect email or password")
                return False

            return True
        else:
            self.password.errors.append("Incorect email or password")
            return False

author/views.py
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from flask import session
from flask import flash

from werkzeug.security import generate_password_hash

from author.models import Author
from author.forms import RegisterForm
from author.forms import LoginForm

from application import db


author_app = Blueprint('author_app', __name__)


@author_app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(full_name=form.full_name.data,
                        email=form.email.data, password=hashed_password)
        db.session.add(author)
        db.session.commit()

        flash("You are now registered, please login")
        return redirect(url_for("author_app.login"))
    return render_template('author/register.html', form=form)


@author_app.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    error = None

    if request.method == "GET" and request.args.get("next"):
        session["next"] = request.args.get("next", None)

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session["id"] = author.id
        session["full_name"] = author.full_name

        if "next" in session:
            redirect_to = session.get("next")
            session.pop("next")
            return redirect(redirect_to)
        else:
            return redirect(url_for("blog_app.index"))

    return render_template("author/login.html", form=form, error=error)


@author_app.route("/logout")
def logout():
    session.pop("id")
    session.pop("full_name")
    flash("User logged out")
    return redirect(url_for("author_app.login"))

templates/author/login.html
{% extends "base.html" %} {% block title %}Author Login{% endblock %} {% block
content %}
<div class="row">
  <div class="offset-md-2 col-md-8">
    {% include '_flashmessages.html' %}

    <h4>Author Login</h4>

    {% from "_formhelpers.html" import render_field %}

    <form method="POST" action="{{ url_for('author_app.login') }}" role="form">
      {{ form.hidden_tag() }} {{ render_field(form.email, class='form-control')
      }} {{ render_field(form.password, class='form-control') }}

      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>
{% endblock %}

templates/author/register.html
{% extends "base.html" %} {% block title %}Author Registration{% endblock %} {%
block content %}
<div class="row">
  <div class="offset-md-2 col-md-8">
    <h4>Author Registration</h4>

    {% from "_formhelpers.html" import render_field %}

    <form
      method="POST"
      action="{{ url_for('author_app.register') }}"
      role="form"
    >
      {{ form.hidden_tag() }} {{ render_field(form.full_name,
      class='form-control') }} {{ render_field(form.email, class='form-control')
      }} {{ render_field(form.password, class='form-control') }} {{
      render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
</div>
{% endblock %}