author/views.py
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from flask import session
from flask import flash

from werkzeug.security import generate_password_hash

from author.models import Author
from author.forms import RegisterForm
from author.forms import LoginForm

from application import db


author_app = Blueprint('author_app', __name__)


@author_app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(full_name=form.full_name.data,
                        email=form.email.data, password=hashed_password)
        db.session.add(author)
        db.session.commit()

        flash("You are now registered, please login")
        return redirect(url_for("author_app.login"))
    return render_template('author/register.html', form=form)


@author_app.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    error = None

    if request.method == "GET" and request.args.get("next"):
        session["next"] = request.args.get("next", None)

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session["id"] = author.id
        session["full_name"] = author.full_name

        if "next" in session:
            redirect_to = session.get("next")
            session.pop("next")
            return redirect(redirect_to)
        else:
            return redirect(url_for("blog_app.index"))

    return render_template("author/login.html", form=form, error=error)


@author_app.route("/logout")
def logout():
    session.pop("id")
    session.pop("full_name")
    flash("User logged out")
    return redirect(url_for("author_app.login"))

blog/views.py
from flask import Blueprint
from flask import session
from flask import render_template
from flask import redirect
from flask import request
from flask import flash
from flask import url_for

from slugify import slugify

from application import db

from blog.models import Post
from blog.models import Category
from blog.models import Tag
from blog.forms import PostForm

from author.models import Author
from author.decorators import login_required

from settings import BLOG_POST_IMAGES_PATH

from uuid import uuid4
import os

from PIL import Image


blog_app = Blueprint('blog_app', __name__)


POSTS_PER_PAGE = 2


@blog_app.route('/')
def index():
    page = int(request.values.get("page", 1))
    posts = Post.query.filter_by(live=True).order_by(
        Post.publish_date.desc()).paginate(page, POSTS_PER_PAGE, False)
    return render_template("blog/index.html", posts=posts, title="Latest Posts")


@blog_app.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    tags_field = request.values.get("tags_field", "")

    if form.validate_on_submit():
        image_id = None

        if form.image.data:
            f = form.image.data
            image_id = str(uuid4())
            file_name = image_id + ".png"
            file_path = os.path.join(BLOG_POST_IMAGES_PATH, file_name)
            Image.open(f).save(file_path)

            image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, "lg")
            image_resize(BLOG_POST_IMAGES_PATH, image_id, 300, "sm")

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            category = new_category
        else:
            category = form.category.data

        author = Author.query.get(session["id"])
        title = form.title.data.strip()
        body = form.body.data.strip()

        post = Post(author=author, title=title, body=body,
                    image=image_id, category=category)

        save_tags(post, tags_field)

        db.session.add(post)
        db.session.commit()

        slug = slugify(str(post.id) + "-" + post.title)
        post.slug = slug
        db.session.commit()

        flash("Article posted")
        return redirect(url_for("blog_app.article", slug=slug))

    return render_template("blog/post.html", form=form, action="new", tags_field=tags_field)


@blog_app.route('/posts/<slug>')
def article(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template("blog/article.html", post=post)


@blog_app.route("/edit/<slug>", methods=["GET", "POST"])
@login_required
def edit(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    tags_field = request.values.get("tags_field", load_tags(post))

    form = PostForm(obj=post)

    if form.validate_on_submit():
        original_image = post.image
        original_title = post.title
        form.populate_obj(post)

        if form.image.data:
            f = form.image.data
            image_id = str(uuid4())
            file_name = image_id + ".png"
            file_path = os.path.join(BLOG_POST_IMAGES_PATH, file_name)
            Image.open(f).save(file_path)

            image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, "lg")
            image_resize(BLOG_POST_IMAGES_PATH, image_id, 300, "sm")

            post.image = image_id
        else:
            post.image = original_image

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            post.category = new_category

        if form.title.data != original_title:
            post.slug = slugify(str(post.id) + "-" + form.title.data)

        save_tags(post, tags_field)

        db.session.commit()
        flash("Article edited")

        return redirect(url_for("blog_app.article", slug=post.slug))

    return render_template("blog/post.html", form=form, post=post, tags_field=tags_field, action="edit")


@blog_app.route("/delete/<slug>")
@login_required
def delete(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    post.live = False
    db.session.commit()

    flash("Article deleted")
    return redirect(url_for("blog_app.index"))


@blog_app.route("/categories/<category_id>")
def categories(category_id):
    category = Category.query.filter_by(id=category_id).first_or_404()
    page = int(request.values.get("page", 1))

    #posts = category.posts.filter_by(live=True).order_by(Post.publish_date.desc()).paginate(page, POSTS_PER_PAGE, False)

    posts = Post.query.filter_by(category=category, live=True)\
        .order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)

    return render_template("blog/category_posts.html", posts=posts, title=category.name, category_id=category_id)


@blog_app.route("/tags/<tag>")
def tags(tag):
    tag = Tag.query.filter_by(name=tag).first_or_404()
    page = int(request.values.get("page", 1))

    posts = tag.posts.filter_by(live=True)\
        .order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)

    return render_template("blog/tag_posts.html", posts=posts, title=f"Tag: {tag.name}", tag=tag.name)


def image_resize(original_file_path, image_id, image_base, extension):
    file_path = os.path.join(original_file_path, image_id + ".png")
    image = Image.open(file_path)

    wpercent = (image_base / float(image.size[0]))
    hsize = int(float(image.size[1]) * float(wpercent))

    image = image.resize((image_base, hsize), Image.ANTIALIAS)
    modified_file_path = os.path.join(
        original_file_path, image_id + "." + extension + ".png")

    image.save(modified_file_path)


def save_tags(post, tags_field):
    post.tags.clear()

    for tag_item in tags_field.split(","):
        tag = Tag.query.filter_by(name=slugify(tag_item)).first()
        if not tag:
            tag = Tag(name=slugify(tag_item))
            db.session.add(tag)
        post.tags.append(tag)

    return post


def load_tags(post):
    tags_field = ""

    for tag in post.tags:
        tags_field += tag.name + ", "

    return tags_field[:-2]

templates/_flashmessages.html
{% with messages = get_flashed_messages() %} {% if messages %}
<div id="messages">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %}
</div>
{% endif %} {% endwith %}

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group mb-3">
  {{ field.label(class='form-label') }} {{ field(**kwargs) | safe }} {% if
  field.errors %}
  <ul class="text-danger mt-3">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
      defer
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %} - {{ config['BLOG_NAME'] }}</title>
  </head>
  <body>
    {% block nav %} {% include 'nav.html' %} {% endblock %}

    <div class="container">
      {% block content %}{% endblock %}

      <div class="offset-md-2 col-md-8 pt-5 pb-3">
        <footer>
          <span class="text-muted">&copy; 2022 {{ config['BLOG_NAME'] }}</span>
        </footer>
      </div>
    </div>
  </body>
</html>

templates/nav.html
<div class="container">
  <div class="row mb-5">
    <div class="offset-md-2 col-md-8">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('blog_app.index') }}">
            {{ config['BLOG_NAME'] }}
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              {% if session.id %}
              <li class="nav-item">
                <span class="navbar-text text-dark d-block">
                  {{ session.full_name }}
                </span>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('blog_app.post') }}" class="nav-link">
                  New Post
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('author_app.logout') }}" class="nav-link">
                  Logout
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a href="{{ url_for('author_app.login') }}" class="nav-link">
                  Login
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>